version: "3.0"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    privileged: true
    ports:
      - "3000:3000/tcp"
    volumes:
      - grafana-data:/var/lib/grafana
      
volumes:
  grafana-data:
