version: "3.0"

services:
  influxdb2:
    container_name: influxdb2
    image: influxdb:2.7.3
    restart: always
    privileged: true
    ports:
      - "8086:8086/tcp"
    volumes:
      - /var/lib/influxdb2:/var/lib/influxdb2 
      - /home/umbrel/umbrel/app-data/influxdb:/data
