version: "3.0"

services:
  influxdb2:
    container_name: influxdb2
    image: influxdb:2.7.3
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /var/lib/influxdb2:/var/lib/influxdb2 
      - /home/umbrel/umbrel/app-data/influxdb:/data
