version: "3.0"

services:
  influxdb2:
    container_name: influxdb2
    image: influxdb:2.7.6
    restart: always
    privileged: true
    ports:
      - "8086:8086/tcp"
    volumes:
      - /home/umbrel/umbrel/app-data/influxdb2/data:/var/lib/influxdb2 
      - /home/umbrel/umbrel/app-data/influxdb2/config:/etc/influxdb2
