version: "3.0"

services:
  homeassistant:
    container_name: homeassistant-container
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /home/umbrel/umbrel/app-data/homeassistant-container/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
