version: "3.0"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    privileged: true
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/umbrel/umbrel/app-data/portainer:/data
