version: "3.0"

services:
  homeassistant:
    container_name: homeassistant-container
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /home/umbrel/umbrel/app-data/homeassistant-container/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/umbrel/umbrel/app-data/portainer:/data
